#!/usr/bin/env bash

set -Eeuo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
tmp="$(mktemp -d "${TMPDIR:-/tmp}/package-cache-control-test.XXXXXX")"
trap 'rm -rf "$tmp"' EXIT

mkdir -p "$tmp/bin" "$tmp/dist" "$tmp/stage"
printf 'current package\n' >"$tmp/dist/widget-1.0.0-1.x86_64.rpm"

cat >"$tmp/bin/gcloud" <<'MOCK'
#!/usr/bin/env bash
set -Eeuo pipefail

log_file="${MOCK_GCLOUD_LOG:?}"
printf '%q ' "$@" >>"$log_file"
printf '\n' >>"$log_file"

case "$*" in
  "storage cp - gs://test-bucket/widget/.publish.lock --if-generation-match=0")
    cat >/dev/null
    ;;
  "storage objects describe gs://test-bucket/widget/.publish.lock --format=value(generation,update_time)")
    printf '12345\t2026-01-01T00:00:00+0000\n'
    ;;
  "storage rsync --recursive gs://test-bucket/widget "*)
    stage_dir="$5"
    mkdir -p \
      "$stage_dir/by-hash/SHA256" \
      "$stage_dir/dists/bookworm" \
      "$stage_dir/legacy"
    printf 'existing dependency\n' >"$stage_dir/dependency-2.0.0-1.x86_64.rpm"
    printf 'immutable index\n' >"$stage_dir/by-hash/SHA256/existing"
    printf 'mutable release metadata\n' >"$stage_dir/dists/bookworm/Release"
    printf 'mutable extension metadata\n' >"$stage_dir/legacy/channel.json"
    ;;
  "storage rsync --recursive --cache-control=asset-contract "*)
    asset_dir="$5"
    while IFS= read -r -d '' asset_file; do
      relative_path="${asset_file#"$asset_dir"/}"
      printf 'ASSET %s\n' "$relative_path" >>"$log_file"
      case "$relative_path" in
        *.deb|*.rpm|*.apk|by-hash/*|*/by-hash/*)
          ;;
        *)
          printf 'Non-asset path was included in the asset rsync: %s\n' "$relative_path" >&2
          exit 1
          ;;
      esac
    done < <(find "$asset_dir" -type f -print0)
    ;;
  "storage cp --cache-control=metadata-contract "*)
    test -f "$4"
    ;;
  "secrets versions access latest "*)
    printf 'test secret\n'
    ;;
  "storage rm gs://test-bucket/widget/.publish.lock --if-generation-match=12345")
    ;;
  *)
    printf 'Unexpected gcloud invocation: %s\n' "$*" >&2
    exit 1
    ;;
esac
MOCK

cat >"$tmp/bin/rpm" <<'MOCK'
#!/usr/bin/env bash
set -Eeuo pipefail

case "${*: -1}" in
  *dependency-*)
    printf 'dependency\n'
    ;;
  *)
    printf 'widget\n'
    ;;
esac
MOCK

cat >"$tmp/bin/gpg" <<'MOCK'
#!/usr/bin/env bash
set -Eeuo pipefail

output=""
while [ "$#" -gt 0 ]; do
  if [ "$1" = "--output" ]; then
    output="$2"
    shift 2
    continue
  fi
  shift
done

if [ -n "$output" ]; then
  printf 'generated by mock gpg\n' >"$output"
else
  printf 'mock public key\n'
fi
MOCK

cat >"$tmp/bin/createrepo_c" <<'MOCK'
#!/usr/bin/env bash
set -Eeuo pipefail

repository_dir="${*: -1}"
mkdir -p "$repository_dir/repodata"
printf 'mutable RPM metadata\n' >"$repository_dir/repodata/repomd.xml"
printf 'mutable RPM metadata payload\n' >"$repository_dir/repodata/primary.xml.gz"
MOCK

chmod +x "$tmp/bin/gcloud" "$tmp/bin/rpm" "$tmp/bin/gpg" "$tmp/bin/createrepo_c"

gcloud_log="$tmp/gcloud.log"
publisher_log="$tmp/publisher.log"
PATH="$tmp/bin:$PATH" \
  MOCK_GCLOUD_LOG="$gcloud_log" \
  DIST_DIR="$tmp/dist" \
  GCLOUD_PROJECT=test-project \
  GCS_BUCKET=test-bucket \
  GCS_BUCKET_PREFIX=widget \
  PACKAGE_NAME=widget \
  PACKAGE_REPO_STAGE_DIR="$tmp/stage" \
  APTLY_GPG_KEY_ID=test-key \
  PACKAGE_ASSET_CACHE_CONTROL=asset-contract \
  PACKAGE_METADATA_CACHE_CONTROL=metadata-contract \
  CDN_INVALIDATE_CACHE=false \
  LOCK_HEARTBEAT_SECONDS=0 \
  bash "$repo_root/scripts/publish-package-repo.sh" >"$publisher_log" 2>&1

grep -Fq "storage rsync --recursive --cache-control=asset-contract " "$gcloud_log"
grep -Fq "ASSET dependency-2.0.0-1.x86_64.rpm" "$gcloud_log"
grep -Fq "ASSET widget-1.0.0-1.x86_64.rpm" "$gcloud_log"
grep -Fq "ASSET by-hash/SHA256/existing" "$gcloud_log"

for metadata_path in \
  "dists/bookworm/Release" \
  "legacy/channel.json" \
  "rpm/repodata/primary.xml.gz" \
  "rpm/repodata/repomd.xml" \
  "rpm/repodata/repomd.xml.asc" \
  "widget-archive-keyring.asc" \
  "widget-archive-keyring.gpg"; do
  grep -Fq \
    "storage cp --cache-control=metadata-contract $tmp/stage/$metadata_path gs://test-bucket/widget/$metadata_path" \
    "$gcloud_log"
done

if grep -Fq "storage objects update" "$gcloud_log"; then
  printf 'Publisher performed redundant per-object cache-control updates\n' >&2
  exit 1
fi

if grep -Fq "Updating cache-control metadata" "$publisher_log"; then
  printf 'Publisher retained the redundant cache-control reconciliation phase\n' >&2
  exit 1
fi
