#!/usr/bin/env bash

set -Eeuo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
tmp="$(mktemp -d "${TMPDIR:-/tmp}/package-publish-exclusion-test.XXXXXX")"
trap 'rm -rf "$tmp"' EXIT

mkdir -p "$tmp/bin" "$tmp/dist" "$tmp/stage" "$tmp/uploaded-metadata"
printf 'current deb package\n' >"$tmp/dist/sitectl_1.0.0_amd64.deb"
printf 'current rpm package\n' >"$tmp/dist/sitectl-1.0.0-1.x86_64.rpm"
printf 'destination-only stale package\n' >"$tmp/stage/sitectl-stale_9.9.9_amd64.deb"

cat >"$tmp/bin/gcloud" <<'MOCK'
#!/usr/bin/env bash
set -Eeuo pipefail

log_file="${MOCK_GCLOUD_LOG:?}"
printf '%q ' "$@" >>"$log_file"
printf '\n' >>"$log_file"

case "$*" in
  "storage cp - gs://test-bucket/sitectl/.publish.lock --if-generation-match=0")
    cat >/dev/null
    ;;
  "storage objects describe gs://test-bucket/sitectl/.publish.lock --format=value(generation,update_time)")
    printf '12345\t2026-01-01T00:00:00+0000\n'
    ;;
  "storage rsync --recursive --delete-unmatched-destination-objects gs://test-bucket/sitectl "*)
    if [ "${MOCK_SYNC_FAILURE:-false}" = "true" ]; then
      printf 'mock repository sync failure\n' >&2
      exit 23
    fi
    stage_dir="$6"
    find "$stage_dir" -mindepth 1 -maxdepth 1 -exec rm -rf -- {} +
    mkdir -p "$stage_dir/rpm" "$stage_dir/dists/bookworm"
    printf 'allowed old deb\n' >"$stage_dir/sitectl-libops_1.3.0_amd64.deb"
    printf 'allowed old rpm\n' >"$stage_dir/sitectl-libops-1.3.0-1.x86_64.rpm"
    printf 'excluded old deb\n' >"$stage_dir/sitectl-isle_0.19.0_amd64.deb"
    printf 'excluded old rpm\n' >"$stage_dir/sitectl-isle-0.19.0-1.x86_64.rpm"
    printf 'excluded nested rpm\n' >"$stage_dir/rpm/sitectl-isle-0.19.0-1.x86_64.rpm"
    printf 'stale metadata\n' >"$stage_dir/dists/bookworm/Release"
    ;;
  "storage rsync --recursive --cache-control=asset-contract "*)
    asset_dir="$5"
    while IFS= read -r -d '' asset_file; do
      relative_path="${asset_file#"$asset_dir"/}"
      printf 'ASSET %s\n' "$relative_path" >>"$log_file"
      if [[ "$relative_path" == *sitectl-isle* ]]; then
        printf 'Excluded asset reached the upload set: %s\n' "$relative_path" >&2
        exit 1
      fi
    done < <(find "$asset_dir" -type f -print0)
    ;;
  "storage cp --cache-control=metadata-contract "*)
    test -f "$4"
    relative_path="${5#gs://test-bucket/sitectl/}"
    uploaded_file="${MOCK_METADATA_DIR:?}/$relative_path"
    mkdir -p "${uploaded_file%/*}"
    cp "$4" "$uploaded_file"
    printf 'METADATA %s\n' "$4" >>"$log_file"
    ;;
  "secrets versions access latest "*)
    printf 'test secret\n'
    ;;
  "storage rm gs://test-bucket/sitectl/.publish.lock --if-generation-match=12345")
    ;;
  "storage rm gs://test-bucket/sitectl/"*)
    printf 'DELETE %s\n' "$3" >>"$log_file"
    ;;
  *)
    printf 'Unexpected gcloud invocation: %s\n' "$*" >&2
    exit 1
    ;;
esac
MOCK

cat >"$tmp/bin/dpkg-deb" <<'MOCK'
#!/usr/bin/env bash
set -Eeuo pipefail

case "${2##*/}" in
  sitectl-isle_*) printf 'sitectl-isle\n' ;;
  sitectl-libops_*) printf 'sitectl-libops\n' ;;
  sitectl_*) printf 'sitectl\n' ;;
  *) exit 1 ;;
esac
MOCK

cat >"$tmp/bin/rpm" <<'MOCK'
#!/usr/bin/env bash
set -Eeuo pipefail

case "${*: -1}" in
  */sitectl-isle-*) printf 'sitectl-isle\n' ;;
  */sitectl-libops-*) printf 'sitectl-libops\n' ;;
  */sitectl-*) printf 'sitectl\n' ;;
  *) exit 1 ;;
esac
MOCK

cat >"$tmp/bin/aptly" <<'MOCK'
#!/usr/bin/env bash
set -Eeuo pipefail

config_path=""
for argument in "$@"; do
  case "$argument" in
    -config=*) config_path="${argument#-config=}" ;;
  esac
done
aptly_root_dir="${config_path%/*}"

if [[ " $* " == *" repo add "* ]]; then
  : >"$aptly_root_dir/mock-debs"
  for argument in "$@"; do
    case "$argument" in
      *.deb) printf '%s\0' "$argument" >>"$aptly_root_dir/mock-debs" ;;
    esac
  done
  exit 0
fi

if [[ " $* " != *" publish snapshot "* ]]; then
  exit 0
fi

mkdir -p "$aptly_root_dir/public/pool/main" "$aptly_root_dir/public/dists/bookworm"
while IFS= read -r -d '' package_file; do
  cp "$package_file" "$aptly_root_dir/public/pool/main/"
done <"$aptly_root_dir/mock-debs"
printf 'mock aptly release\n' >"$aptly_root_dir/public/dists/bookworm/Release"
MOCK

cat >"$tmp/bin/dpkg-scanpackages" <<'MOCK'
#!/usr/bin/env bash
set -Eeuo pipefail

while IFS= read -r -d '' package_file; do
  package_name="$(dpkg-deb -f "$package_file" Package)"
  printf 'Package: %s\nFilename: %s\n\n' "$package_name" "$package_file"
done < <(find pool -type f -name '*.deb' -print0 | sort -z)
MOCK

cat >"$tmp/bin/gpg" <<'MOCK'
#!/usr/bin/env bash
set -Eeuo pipefail

output=""
while [ "$#" -gt 0 ]; do
  if [ "$1" = "--output" ]; then
    output="$2"
    shift 2
    continue
  fi
  shift
done

if [ -n "$output" ]; then
  printf 'generated by mock gpg\n' >"$output"
else
  printf 'mock public key\n'
fi
MOCK

cat >"$tmp/bin/createrepo_c" <<'MOCK'
#!/usr/bin/env bash
set -Eeuo pipefail

repository_dir="${*: -1}"
mkdir -p "$repository_dir/repodata"
find "$repository_dir" -maxdepth 1 -type f -name '*.rpm' -printf '%f\n' \
  | sort >"$repository_dir/repodata/primary.xml"
printf 'mock RPM repository\n' >"$repository_dir/repodata/repomd.xml"
MOCK

chmod +x "$tmp/bin/"*

gcloud_log="$tmp/gcloud.log"
publisher_log="$tmp/publisher.log"
if ! PATH="$tmp/bin:$PATH" \
  MOCK_GCLOUD_LOG="$gcloud_log" \
  MOCK_METADATA_DIR="$tmp/uploaded-metadata" \
  DIST_DIR="$tmp/dist" \
  GCLOUD_PROJECT=test-project \
  GCS_BUCKET=test-bucket \
  GCS_BUCKET_PREFIX=sitectl \
  PACKAGE_NAME=sitectl \
  EXCLUDED_PACKAGE_NAMES='sitectl-isle, sitectl-preview' \
  PACKAGE_REPO_STAGE_DIR="$tmp/stage" \
  APTLY_GPG_KEY_ID=test-key \
  PACKAGE_ASSET_CACHE_CONTROL=asset-contract \
  PACKAGE_METADATA_CACHE_CONTROL=metadata-contract \
  CDN_INVALIDATE_CACHE=false \
  LOCK_HEARTBEAT_SECONDS=0 \
  bash "$repo_root/scripts/publish-package-repo.sh" >"$publisher_log" 2>&1; then
  cat "$publisher_log" >&2
  cat "$gcloud_log" >&2
  exit 1
fi

for excluded_path in \
  "sitectl-isle_0.19.0_amd64.deb" \
  "sitectl-isle-0.19.0-1.x86_64.rpm" \
  "rpm/sitectl-isle-0.19.0-1.x86_64.rpm"; do
  grep -Fq "Pruning excluded package artifact $excluded_path (sitectl-isle)" "$publisher_log"
  grep -Fq "DELETE gs://test-bucket/sitectl/$excluded_path" "$gcloud_log"
done

if grep -Fn 'sitectl-isle' \
  "$tmp/uploaded-metadata/Packages" \
  "$tmp/uploaded-metadata/rpm/repodata/primary.xml"; then
  printf 'Excluded package remained in replacement repository metadata\n' >&2
  exit 1
fi
if grep -Fq 'sitectl-stale' "$gcloud_log" ||
  grep -Fq 'sitectl-stale' "$tmp/uploaded-metadata/Packages"; then
  printf 'Destination-only stale package survived the clean repository sync\n' >&2
  exit 1
fi

grep -Fq "Package: sitectl" "$tmp/uploaded-metadata/Packages"
grep -Fq "Package: sitectl-libops" "$tmp/uploaded-metadata/Packages"
grep -Fq "sitectl-1.0.0-1.x86_64.rpm" "$tmp/uploaded-metadata/rpm/repodata/primary.xml"
grep -Fq "sitectl-libops-1.3.0-1.x86_64.rpm" "$tmp/uploaded-metadata/rpm/repodata/primary.xml"

last_metadata_line="$(grep -n '^METADATA ' "$gcloud_log" | tail -n1 | cut -d: -f1)"
first_delete_line="$(grep -n '^DELETE ' "$gcloud_log" | head -n1 | cut -d: -f1)"
if [ -z "$last_metadata_line" ] || [ -z "$first_delete_line" ] ||
  [ "$first_delete_line" -le "$last_metadata_line" ]; then
  printf 'Excluded objects were not deleted after all replacement metadata uploads\n' >&2
  exit 1
fi

mkdir -p "$tmp/rejected-dist" "$tmp/rejected-stage"
printf 'excluded current artifact\n' \
  >"$tmp/rejected-dist/sitectl-isle-0.19.0-1.x86_64.rpm"
: >"$tmp/rejected-gcloud.log"
if PATH="$tmp/bin:$PATH" \
  MOCK_GCLOUD_LOG="$tmp/rejected-gcloud.log" \
  DIST_DIR="$tmp/rejected-dist" \
  GCLOUD_PROJECT=test-project \
  GCS_BUCKET=test-bucket \
  GCS_BUCKET_PREFIX=sitectl \
  PACKAGE_NAME=sitectl \
  EXCLUDED_PACKAGE_NAMES=sitectl-isle \
  PACKAGE_REPO_STAGE_DIR="$tmp/rejected-stage" \
  APTLY_GPG_KEY_ID=test-key \
  LOCK_HEARTBEAT_SECONDS=0 \
  bash "$repo_root/scripts/publish-package-repo.sh" \
    >"$tmp/rejected-publisher.log" 2>&1; then
  printf 'Excluded current release artifact unexpectedly reached publication\n' >&2
  exit 1
fi
grep -Fq "has excluded package name 'sitectl-isle'" "$tmp/rejected-publisher.log"
if [ -s "$tmp/rejected-gcloud.log" ]; then
  printf 'Excluded current release artifact reached Google Cloud operations\n' >&2
  exit 1
fi

mkdir -p "$tmp/sync-failure-stage"
: >"$tmp/sync-failure-gcloud.log"
if PATH="$tmp/bin:$PATH" \
  MOCK_GCLOUD_LOG="$tmp/sync-failure-gcloud.log" \
  MOCK_SYNC_FAILURE=true \
  DIST_DIR="$tmp/dist" \
  GCLOUD_PROJECT=test-project \
  GCS_BUCKET=test-bucket \
  GCS_BUCKET_PREFIX=sitectl \
  PACKAGE_NAME=sitectl \
  EXCLUDED_PACKAGE_NAMES=sitectl-isle \
  PACKAGE_REPO_STAGE_DIR="$tmp/sync-failure-stage" \
  APTLY_GPG_KEY_ID=test-key \
  LOCK_HEARTBEAT_SECONDS=0 \
  bash "$repo_root/scripts/publish-package-repo.sh" \
    >"$tmp/sync-failure-publisher.log" 2>&1; then
  printf 'Failed repository sync unexpectedly continued publication\n' >&2
  exit 1
fi
grep -Fq \
  "refusing to replace metadata from partial state" \
  "$tmp/sync-failure-publisher.log"
grep -Fq \
  "storage rsync --recursive --delete-unmatched-destination-objects gs://test-bucket/sitectl" \
  "$tmp/sync-failure-gcloud.log"
for forbidden_operation in \
  "secrets versions access" \
  "--cache-control=" \
  "compute url-maps invalidate-cdn-cache" \
  "DELETE gs://"; do
  if grep -Fq -- "$forbidden_operation" "$tmp/sync-failure-gcloud.log"; then
    printf 'Repository sync failure reached forbidden operation: %s\n' \
      "$forbidden_operation" >&2
    exit 1
  fi
done
