name: build-push

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - .github/workflows/build-push.yaml

jobs:
  run:
    uses: libops/.github/.github/workflows/build-push.yaml@d7f0ba06b4c8a1f8559892ea65a0b1af4d024dd3 # main
    permissions:
      contents: read
      packages: write
    secrets: inherit
