name: build-push

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - .github/workflows/build-push.yaml

jobs:
  run:
    uses: libops/.github/.github/workflows/build-push.yaml@f79884c560c7abc417c7aae3be2f890fb47e1a1f # main
    permissions:
      contents: read
      packages: write
    secrets: inherit
